### ISSUE TITLE
Snap 版后续还维护吗？

### ISSUE THREAD

**Issue by gapplef** [Fclash/Fclash#41]
首先，感谢为Linux提供简单好用的clash软件。

之前一直用的snap版，挺省心的。最近换电脑重装系统，遇到了无法修改系统代理的问题，手动修改后倒是不影响使用。
搜了下发现snap已经落后好多版本了，请问后续snap版还会维护吗？

看到代码库中有自动构建和推送Snap的Action，是什么原因停用了呢？后续还会维护吗？

**Comment by Kingtous** [comment]
snap ci遇到了flutter的问题，后续考虑换成flatpak

**Comment by gapplef** [comment]
感谢回复！请问具体问题是？
我不是很清楚snap的构建，不过有空可以尝试下。
目前不少软件都用的snap版，体验还是挺好的。

**Comment by Kingtous** [comment]
snap上游一直没有解决flutter编译问题，需要升级core20，但flutter目前snap只支持core18. 等snap啥时候激进点再更新

**Comment by gapplef** [comment]
我简单试了下，能编译，但编译时出错，似乎是缺少文件？
```
:: [ +115 ms] -- Configuring done
:: [ +136 ms] CMake Error in flutter/ephemeral/.plugin_symlinks/tray_manager/linux/CMakeLists.txt:
:: [   +1 ms]   Imported target "PkgConfig::APPINDICATOR" includes non-existent path
:: [        ]     "/usr/include/libayatana-appindicator3-0.1"
:: [        ]   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
:: [        ]   * The path was deleted, renamed, or moved to another location.
:: [        ]   * An install or uninstall procedure did not complete successfully.
:: [        ]   * The installation package was faulty and references files it does not
:: [        ]   provide.
:: [  +34 ms] CMake Warning at flutter/ephemeral/.plugin_symlinks/tray_manager/linux/CMakeLists.txt:11 (add_library):
:: [        ]   Cannot generate a safe runtime search path for target tray_manager_plugin
:: [        ]   because files in some directories may conflict with libraries in implicit
:: [        ]   directories:
:: [        ]     runtime library [libdbusmenu-glib.so.4] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
:: [        ]       /snap/gnome-42-2204-sdk/current/usr/lib/x86_64-linux-gnu
:: [        ]     runtime library [libgtk-3.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
:: [        ]       /snap/gnome-42-2204-sdk/current/usr/lib/x86_64-linux-gnu
:: [        ]     runtime library [libgdk-3.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
:: [        ]       /snap/gnome-42-2204-sdk/current/usr/lib/x86_64-linux-gnu
:: [        ]     runtime library [libpangocairo-1.0.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
:: [        ]       /snap/gnome-42-2204-sdk/current/usr/lib/x86_64-linux-gnu
:: [        ]     runtime library [libpango-1.0.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
:: [        ]       /snap/gnome-42-2204-sdk/current/usr/lib/x86_64-linux-gnu
:: [        ]     runtime library [libharfbuzz.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
:: [        ]       /snap/gnome-42-2204-sdk/current/usr/lib/x86_64-linux-gnu
:: [        ]     runtime library [libatk-1.0.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
:: [        ]       /snap/gnome-42-2204-sdk/current/usr/lib/x86_64-linux-gnu
:: [        ]     runtime library [libcairo-gobject.so.2] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
:: [        ]       /snap/gnome-42-2204-sdk/current/usr/lib/x86_64-linux-gnu
:: [        ]     runtime library [libcairo.so.2] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
:: [        ]       /snap/gnome-42-2204-sdk/current/usr/lib/x86_64-linux-gnu
:: [        ]     runtime library [libgdk_pixbuf-2.0.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
:: [        ]       /snap/gnome-42-2204-sdk/current/usr/lib/x86_64-linux-gnu
:: [        ]     runtime library [libgio-2.0.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
:: [        ]       /snap/gnome-42-2204-sdk/current/usr/lib/x86_64-linux-gnu
:: [        ]     runtime library [libgobject-2.0.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
:: [        ]       /snap/gnome-42-2204-sdk/current/usr/lib/x86_64-linux-gnu
:: [        ]     runtime library [libglib-2.0.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
:: [        ]       /snap/gnome-42-2204-sdk/current/usr/lib/x86_64-linux-gnu
:: [        ]   Some of these libraries may not be found correctly.
:: [  +14 ms] -- Generating done
:: [   +5 ms] CMake Generate step failed.  Build files cannot be regenerated correctly.
:: [   +6 ms] Building Linux application... (completed in 1,131ms)
:: [        ] "flutter linux" took 52,726ms.
:: [   +2 ms] Unable to generate build files
```

**Comment by Kingtous** [comment]
需要安装`libayatana-appindicator3`这个依赖包

**Comment by gapplef** [comment]
我看到snapcraft.yml中是有libappindicator3的，这个libayatana-appindicator3是前者的替代吗？

**Comment by Kingtous** [comment]
> 我看到snapcraft.yml中是有libappindicator3的，这个libayatana-appindicator3是前者的替代吗？

是的，前者很久没更新了

**Comment by Kingtous** [comment]
> 

感谢一直在尝试这个，最近比较忙，就没看了。这个貌似是gnome的，如果有兴趣的话，可以尝试用flatpak打包。flatpak是趋势。

**Comment by gapplef** [comment]
确实开源社区总体对flatpak的态度更积极，开源应用也更多些。

不过，我用的Ubuntu系统，日常应用也都能被snap覆盖，暂时没有动力切换flatpak。
我在snapcraft社区里发了求助，希望能有人能提供帮助。

**Comment by Kingtous** [comment]
非常感谢你对这个项目提供了非常大的帮助！

**Comment by gapplef** [comment]
主要想处理下snap打包，方便后续使用，可惜没能解决问题 :joy: 
之前就想了解snap打包，刚好也借这个机会学了下。

**Comment by gapplef** [comment]
查了下，Snapcraft经历一次[重构](https://canonical.com/blog/the-future-of-snapcraft)，所以出现了扩展不兼容的问题，core 22之前的版本现在为snapcraft_legacy用于旧版core。

我找到了扩展和插件的源码，可以看到它们具体在干什么：snapcraft的[gnome extension](https://github.com/snapcore/snapcraft/blob/main/snapcraft/extensions/gnome.py)会配置gnome-sdk、添加plug、设置环境变量。snapcraft_legacy的[flutter extension](https://github.com/snapcore/snapcraft/blob/main/snapcraft_legacy/internal/project_loader/_extensions/_flutter_meta.py)相比前者只是多了安装flutter snap，[plugin](https://github.com/snapcore/snapcraft/blob/main/snapcraft_legacy/plugins/v1/flutter.py)则实现路径配置及flutter build。新版[flutter plugin](https://github.com/snapcore/snapcraft/blob/main/snapcraft/parts/plugins/flutter_plugin.py)会在build部分安装flutter，并运行flutter build，整体作用类似于：
```yaml
parts:
  <part_name>:
    plugin: nil
    override-build: |
      git clone --depth 1 -b stable https://github.com/flutter/flutter.git <flutter_dir>
      export PATH="<flutter_dir>/bin:$PATH"
      flutter precache --linux
      flutter pub get
      flutter build linux --release -v
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL
    build-packages:
      - git
      - clang
      - cmake
      - ninja-build
      - unzip
```
如果自定义build，`override-build`部分会被覆盖，只有`build-packages`部分起作用，完全没有必要用plugin。
之前的猜测基本是正确的，不过可能是因为classic模式，flutter需要从源码装，在build-snaps中加flutter有问题。

**Comment by gapplef** [comment]
所有的依赖问题最后证明都是gnome-extension的bug https://github.com/ubuntu/gnome-sdk/issues/121
经过简化，以下`snapcraft.yaml`可正确构建，运行也没问题，我可以整理下开个pr
原`snapcraft.yaml`中的大部分`plugs`是不需要的，[gnome-extension](https://snapcraft.io/docs/gnome-extension)会自动添加。
```yaml
....

parts:
  fclash:
    plugin: nil
    source: .
    build-snaps: [go]
    override-build: |
      ./build-clash-lib.py
      git clone --depth 1 -b stable https://github.com/flutter/flutter.git /root/flutter
      export PATH="/root/flutter/bin:$PATH"
      flutter pub get
      flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/usr/bin/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/usr/bin
    build-packages:
      - python3
      - git
      - clang
      - cmake
      - ninja-build
      - unzip

apps:
  fclash:
    command: usr/bin/fclash
    # desktop: meta/gui/fclash.desktop
    extensions: [ gnome ]
    plugs:
      - home
      - network
      - unity7
      # manually connect by snap
      - system-observe
      - network-observe
      - network-control
      - network-status
      # end clash subprocess
      - process-control
```
